Repository woowa-techcamp-2021/store-7, pull requests merged in 2021-08, with the labels that each got.

#4 chore: webpack/babel 설정
  client/.babelrc
  client/config/webpack.config.common.js
  client/config/webpack.config.dev.js
  client/config/webpack.config.prod.js
  client/package.json
  client/src/Components/Header.tsx
  client/src/Pages/Main.tsx
  client/src/index.tsx
  client/src/styles/global-style.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/tsconfig.json
  client/yarn.lock
Labels: FE

#5 feat: Header 작성
  client/src/App.tsx
  client/src/Components/Header.tsx
  client/src/Components/Input.tsx
  client/src/Components/Menu.tsx
  client/src/Pages/Main.tsx
  client/src/hooks/useInput.ts
  client/src/styles/global-style.ts
  client/tsconfig.json
Labels: FE

#6 feat: 라우터 구현
  client/src/App.tsx
  client/src/Router.tsx
Labels: FE

#7 feat: css 수정
  .prettierrc
  client/config/webpack.config.common.js
  client/package.json
  client/src/Components/Header.tsx
  client/src/Components/Menu.tsx
  client/src/Pages/Login.tsx
  client/src/Pages/Main.tsx
  client/src/Pages/Signup.tsx
  client/src/shared/styled.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/yarn.lock
Labels: FE

#8 feat: 전체적인 CSS 수정 및 카테고리/상세 페이지 마크업
  client/config/webpack.config.common.js
  client/custom.d.ts
  client/package.json
  client/src/App.tsx
  client/src/Components/Button.tsx
  client/src/Components/Header.tsx
  client/src/Components/Input.tsx
  client/src/Components/Menu.tsx
  client/src/Pages/Cart.tsx
  client/src/Pages/Category.tsx
  client/src/Pages/Detail.tsx
  client/src/Pages/Main.tsx
  client/src/Router.tsx
  client/src/assets/hamburger.svg
  client/src/assets/index.ts
  client/src/index.tsx
  client/src/shared/styled.ts
  client/src/styles/global-style.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/yarn.lock
Labels: FE

#9 update: globalStyle의 폰트 관련 theme로 이동
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: FE

#10 feat: DetailPage 마크업
  client/src/Components/Header.tsx
  client/src/Pages/Detail.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/index.tsx
  client/src/styles/global-style.ts
Labels: FE

#12 [FE] 메인페이지 레이아웃 작업 중...!
  .gitignore
  client/src/Pages/Main/Banner.tsx
  client/src/Pages/Main/index.tsx
  client/src/assets/banner1.gif
  client/src/assets/banner2.gif
  client/src/assets/banner3.gif
Labels: FE

#13 [FE] 라우터 ...!
  client/src/Router.tsx
Labels: FE

#14 feat: DetailPage 작업
  client/package.json
  client/src/Components/Button.tsx
  client/src/Components/Footer.tsx
  client/src/Components/Header.tsx
  client/src/Pages/Cart.tsx
  client/src/Pages/Category.tsx
  client/src/Pages/Detail/Guide.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/Question.tsx
  client/src/Pages/Detail/Review.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Main/index.tsx
  client/src/shared/styled.ts
  client/src/styles/global-style.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/yarn.lock
Labels: FE

#15 [FE] 메인 페이지 작업중 에러 해결
  client/src/Components/Header.tsx
  client/src/Components/Header/Menu.tsx
  client/src/Components/Header/Search.tsx
  client/src/Components/Header/index.tsx
  client/src/Pages/Main/Banner.tsx
  client/src/Pages/Main/index.tsx
  client/src/assets.d.ts
  client/src/assets/index.ts
  client/src/assets/logo.png
  client/src/assets/menu.svg
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: FE

#16 feat: 상품후기/문의 수정
  client/package.json
  client/src/App.tsx
  client/src/Components/ETProgress.tsx
  client/src/Components/ETRating.tsx
  client/src/Components/Footer.tsx
  client/src/Components/Item.tsx
  client/src/Pages/Category.tsx
  client/src/Pages/Detail/Question.tsx
  client/src/Pages/Detail/QuestionBox.tsx
  client/src/Pages/Detail/Review.tsx
  client/src/Pages/Detail/ReviewBox.tsx
  client/src/Pages/Detail/index.tsx
  client/src/shared/styled.ts
  client/src/shared/type.ts
  client/src/styles/global-style.ts
  client/yarn.lock
Labels: FE

#17 [FE] 헤더 마크업 완성
  client/src/App.tsx
  client/src/Components/Header/Menu.tsx
  client/src/Components/Header/Search.tsx
  client/src/Components/Header/index.tsx
  client/src/Pages/Main/index.tsx
  client/src/shared/styled.ts
  client/src/utils/node.ts
Labels: FE

#18 mypage / table 컴포넌트
  client/config/webpack.config.common.js
  client/package.json
  client/src/App.tsx
  client/src/Pages/MyPage/Table.tsx
  client/src/Pages/MyPage/index.tsx
  client/yarn.lock
Labels: FE

#20 feat: Detail Page의 후기/문의 모달 작성 및 css 수정
  client/src/Components/ETRating.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/ModalWrapper.tsx
  client/src/Pages/Detail/Question.tsx
  client/src/Pages/Detail/QuestionModal.tsx
  client/src/Pages/Detail/Review.tsx
  client/src/Pages/Detail/ReviewBox.tsx
  client/src/Pages/Detail/ReviewModal.tsx
  client/src/Pages/Detail/index.tsx
  client/src/assets/close.svg
  client/src/assets/index.ts
  client/src/hooks/useInput.ts
  client/src/styles/global-style.ts
Labels: FE

#21 [FE] 로그인 페이지 목업 완료
  client/src/Components/Button.tsx
  client/src/Pages/Login.tsx
Labels: FE

#22 [FE] 라우터 뒤로가기 적용
  client/src/Router.tsx
Labels: FE

#23 feat: DetailPage 수정
  client/src/App.tsx
  client/src/Pages/Detail/Question/QuestionBox.tsx
  client/src/Pages/Detail/Question/QuestionModal.tsx
  client/src/Pages/Detail/Question/index.tsx
  client/src/Pages/Detail/Review/ReviewBox.tsx
  client/src/Pages/Detail/Review/ReviewModal.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/Pages/Detail/index.tsx
Labels: FE

#25 feat: 주소 검색 및 입력 컴포넌트 구현
  client/package.json
  client/src/App.tsx
  client/src/Components/Address/Popup.tsx
  client/src/Components/Address/index.tsx
  client/src/Pages/Signup.tsx
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: FE

#26 feat: 장바구니 수정 및 결제페이지 작성
  client/src/App.tsx
  client/src/Components/Button.tsx
  client/src/Components/ModalWrapper.tsx
  client/src/Pages/Cart.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/MyPage/index.tsx
  client/src/Pages/Order.tsx
  client/src/Pages/OrderBox.tsx
  client/src/styles/global-style.ts
  client/yarn.lock
Labels: FE

#27 feat: OrderPage 수정
  client/src/App.tsx
  client/src/Components/Header/index.tsx
  client/src/Pages/Collection.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Order/OrderBox.tsx
  client/src/Pages/Order/index.tsx
  client/src/styles/global-style.ts
Labels: FE

#28 chore: svg 설정
  client/config/webpack.config.common.js
Labels: FE, Setting

#29 feat: 장바구니/결제 아이템 박스 수정 및 공통 type 분리
  client/src/Components/Address/Popup.tsx
  client/src/Components/Address/index.tsx
  client/src/Components/ItemInfoBox.tsx
  client/src/Pages/Cart.tsx
  client/src/Pages/Cart/CartBox.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Order/AddressBox.tsx
  client/src/Pages/Order/AddressModal.tsx
  client/src/Pages/Order/index.tsx
  client/src/Pages/Signup.tsx
  client/src/shared/dummy.ts
  client/src/shared/styled.ts
  client/src/shared/type.ts
Labels: FE

#32 [FE] 회원가입 페이지 마크업
  client/src/Components/Address/index.tsx
  client/src/Components/Input/InputSection.tsx
  client/src/Components/Input/ValidationInput.tsx
  client/src/Components/Input/index.tsx
  client/src/Pages/Login.tsx
  client/src/Pages/MyPage/Table/index.tsx
  client/src/Pages/Signup.tsx
  client/src/hooks/useInput.ts
  client/src/hooks/useValidation.ts
  client/src/styles/global-style.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/utils/validations.ts
Labels: FE

#33 feat: 버튼 수정 / 배송지 모달 작성
  client/custom.d.ts
  client/src/Components/Button.tsx
  client/src/Components/Footer.tsx
  client/src/Pages/Cart/CartBox.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Order/AddressBox.tsx
  client/src/Pages/Order/AddressModal.tsx
  client/src/Pages/Order/OrderBox.tsx
  client/src/Pages/Order/index.tsx
  client/src/Pages/Signup.tsx
  client/src/assets.d.ts
  client/src/assets/arrow.svg
  client/src/assets/back.svg
  client/src/assets/index.ts
  client/src/shared/dummy.ts
  client/src/shared/type.ts
Labels: FE

#34 feat: Item wish 아이콘 추가
  client/src/Components/Item.tsx
  client/src/assets/index.ts
  client/src/assets/wish.svg
  client/src/shared/dummy.ts
Labels: FE

#35 feat: 결제 페이지 관련 폼 작성
  client/src/Components/Button.tsx
  client/src/Components/Checkbox.tsx
  client/src/Components/ItemInfoBox.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Order/AddressForm.tsx
  client/src/Pages/Order/AddressModal.tsx
  client/src/Pages/Order/index.tsx
  client/src/Pages/Signup.tsx
  client/src/assets/check.svg
  client/src/assets/index.ts
  client/src/shared/dummy.ts
  client/src/styles/global-style.ts
  client/src/utils/validations.ts
Labels: FE

#36 기타 수정 사항
  client/src/Components/Item.tsx
  client/src/Components/ModalWrapper.tsx
  client/src/Components/SignatureLine.tsx
  client/src/Pages/MyPage/Content/index.tsx
  client/src/Pages/MyPage/Section.tsx
  client/src/Pages/MyPage/Sidebar/index.tsx
  client/src/Pages/MyPage/Table/index.tsx
  client/src/Pages/MyPage/Table/tableForm.tsx
  client/src/Pages/MyPage/index.tsx
  client/src/assets/index.ts
  client/src/shared/styled.ts
Labels: FE

#37 [FE] 메인페이지 마크업 완료
  client/src/Pages/Detail/Review/ReviewBox.tsx
  client/src/Pages/Main/BannerSection/Banner.tsx
  client/src/Pages/Main/BannerSection/index.tsx
  client/src/Pages/Main/GiftSection/Gift.tsx
  client/src/Pages/Main/GiftSection/GiftList.tsx
  client/src/Pages/Main/GiftSection/index.tsx
  client/src/Pages/Main/ProductSection/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewList.tsx
  client/src/Pages/Main/ReviewSection/index.tsx
  client/src/Pages/Main/index.tsx
  client/src/assets/secretpen.png
  client/src/assets/tray.png
  client/src/shared/dummy.ts
  client/src/shared/type.ts
Labels: FE

#38 feat: DetailPage 이미지 확대 구현
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/ZoomModal.tsx
  client/src/Pages/Detail/index.tsx
  client/src/assets/index.ts
  client/src/assets/triangle.svg
  client/src/utils/util.ts
Labels: FE

#42 마이페이지 화면 전환
  client/src/Components/Header/index.tsx
  client/src/Components/Item.tsx
  client/src/Components/SignatureLine.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/MyPage/Content/RecentOrderRow.tsx
  client/src/Pages/MyPage/Content/Temp.tsx
  client/src/Pages/MyPage/Content/index.tsx
  client/src/Pages/MyPage/Section.tsx
  client/src/Pages/MyPage/Sidebar/index.tsx
  client/src/Pages/MyPage/Table/index.tsx
  client/src/Pages/MyPage/Table/tableForm.tsx
  client/src/Pages/MyPage/index.tsx
  client/src/shared/dummy.ts
  client/src/utils/util.ts
Labels: FE

#45 chore: 데모용정리
  client/.eslintrc
  client/.gitignore
  client/src/Components/Item.tsx
  client/src/index.html
Labels: FE

#52 Feature/foldering
  client/config/webpack.config.common.js
  client/package.json
  client/src/Components/Item.tsx
  client/src/Pages/Category.tsx
  client/src/Pages/Detail/Question/QuestionBox.tsx
  client/src/Pages/MyPage/Content/Temp.tsx
  client/src/Pages/MyPage/Content/index.tsx
  client/src/Pages/MyPage/ContentArea/Contents/OrderList.tsx
  client/src/Pages/MyPage/ContentArea/Contents/Question.tsx
  client/src/Pages/MyPage/ContentArea/Contents/Review.tsx
  client/src/Pages/MyPage/ContentArea/Contents/Root.tsx
  client/src/Pages/MyPage/ContentArea/Contents/UserInfo.tsx
  client/src/Pages/MyPage/ContentArea/Contents/WishList.tsx
  client/src/Pages/MyPage/ContentArea/Contents/index.ts
  client/src/Pages/MyPage/ContentArea/index.tsx
  client/src/Pages/MyPage/Table/Row/Empty.tsx
  client/src/Pages/MyPage/Table/Row/Question.tsx
  client/src/Pages/MyPage/Table/Row/RecentOrder.tsx
  client/src/Pages/MyPage/Table/Row/Review.tsx
  client/src/Pages/MyPage/Table/Row/index.ts
  client/src/Pages/MyPage/Table/tableForm.tsx
  client/src/Pages/MyPage/index.tsx
  client/src/shared/dummy.ts
  client/src/shared/styled.ts
  client/src/shared/type.ts
  client/tsconfig.json
  client/yarn.lock
Labels: FE, Setting

#49 test: 공통 컴포넌트 테스트코드 작성
  client/package.json
  client/src/App.tsx
  client/src/Components/Button/Button.test.tsx
  client/src/Components/Button/index.tsx
  client/src/Components/Checkbox/Checkbox.test.tsx
  client/src/Components/Checkbox/index.tsx
  client/src/Components/Footer/Footer.test.tsx
  client/src/Components/Footer/index.tsx
  client/src/Components/ItemInfoBox/ItemInfoBox.test.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Components/ModalWrapper/ModalWrapper.test.tsx
  client/src/Components/ModalWrapper/index.tsx
  client/src/Components/Progress/Progress.test.tsx
  client/src/Components/Progress/index.tsx
  client/src/Components/Rating/Rating.test.tsx
  client/src/Components/Rating/index.tsx
  client/src/Pages/Collection.tsx
  client/src/Pages/Detail/Review/ReviewBox.tsx
  client/src/Pages/Detail/Review/ReviewModal.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/utils/test-util.tsx
  client/tsconfig.json
  client/yarn.lock
Labels: FE

#53 refactor/header
  client/src/Components/Header/Menu.tsx
  client/src/Components/Header/Search/AutoCompleteList.tsx
  client/src/Components/Header/Search/SearchList.tsx
  client/src/Components/Header/Search/index.tsx
Labels: FE

#54 [FE] Refactor/fix cross browsing issue
  client/src/Components/Address/index.tsx
  client/src/Components/Footer/index.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/Input/InputSection.tsx
  client/src/Components/Input/ValidationInput.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Cart/CartBox.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/Question/QuestionBox.tsx
  client/src/Pages/Detail/Question/QuestionModal.tsx
  client/src/Pages/Detail/Review/ReviewBox.tsx
  client/src/Pages/Detail/Review/ReviewModal.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Login.tsx
  client/src/Pages/Main/BannerSection/Banner.tsx
  client/src/Pages/Main/GiftSection/Gift.tsx
  client/src/Pages/Main/GiftSection/GiftList.tsx
  client/src/Pages/Main/ReviewSection/ReviewList.tsx
  client/src/Pages/Main/index.tsx
  client/src/Pages/Order/AddressBox.tsx
  client/src/Pages/Order/AddressForm.tsx
  client/src/Pages/Order/AddressModal.tsx
  client/src/Pages/Order/OrderBox.tsx
  client/src/Pages/Order/index.tsx
  client/src/Pages/Signup.tsx
  client/src/shared/styled.ts
  client/src/styles/theme.ts
Labels: FE

#55 [FE] Refactor/router
  client/src/App.tsx
  client/src/Components/Header/Menu.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/Item.tsx
  client/src/Pages/Login.tsx
  client/src/Pages/Main/BannerSection/Banner.tsx
  client/src/Pages/Main/GiftSection/Gift.tsx
  client/src/Pages/Main/ReviewSection/ReviewList.tsx
  client/src/Pages/MyPage/Sidebar/index.tsx
  client/src/Pages/MyPage/Table/tableForm.tsx
  client/src/Pages/Signup.tsx
  client/src/Router.tsx
Labels: FE

#56 test: 주문결제/장바구니/상세 페이지 테스트코드 작성
  client/package.json
  client/src/Components/Button/Button.test.tsx
  client/src/Components/Checkbox/Checkbox.test.tsx
  client/src/Components/ItemInfoBox/ItemInfoBox.test.tsx
  client/src/Components/ModalWrapper/ModalWrapper.test.tsx
  client/src/Components/ModalWrapper/index.tsx
  client/src/Components/Progress/Progress.test.tsx
  client/src/Pages/Cart/Cart.test.tsx
  client/src/Pages/Cart/CartBox/CartBox.test.tsx
  client/src/Pages/Cart/CartBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/Detail.test.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/Question/Question.test.tsx
  client/src/Pages/Detail/Question/QuestionBox/QuestionBox.test.tsx
  client/src/Pages/Detail/Question/QuestionBox/index.tsx
  client/src/Pages/Detail/Question/QuestionModal/QuestionModal.test.tsx
  client/src/Pages/Detail/Question/QuestionModal/index.tsx
  client/src/Pages/Detail/Review/Review.test.tsx
  client/src/Pages/Detail/Review/ReviewBox/ReviewBox.test.tsx
  client/src/Pages/Detail/Review/ReviewBox/index.tsx
  client/src/Pages/Detail/Review/ReviewModal/ReviewModal.test.tsx
  client/src/Pages/Detail/Review/ReviewModal/index.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/Pages/Detail/ZoomModal.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Order/AddressBox/AddressBox.test.tsx
  client/src/Pages/Order/AddressBox/index.tsx
  client/src/Pages/Order/AddressForm/AddressForm.test.tsx
  client/src/Pages/Order/AddressForm/index.tsx
  client/src/Pages/Order/AddressModal/AddressModal.test.tsx
  client/src/Pages/Order/AddressModal/index.tsx
  client/src/Pages/Order/Order.test.tsx
  client/src/Pages/Order/OrderBox/OrderBox.test.tsx
  client/src/Pages/Order/OrderBox/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/shared/dummy.ts
  client/src/shared/type.ts
  client/src/utils/util.ts
  client/tsconfig.json
  client/yarn.lock
Labels: FE

#57 chore: recoil setup
  client/package.json
  client/src/Components/ModalWrapper/ModalWrapper.test.tsx
  client/src/Components/ModalWrapper/index.tsx
  client/src/Pages/Detail/Question/index.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Order/AddressModal/AddressModal.test.tsx
  client/src/Pages/Order/AddressModal/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/index.tsx
  client/src/store/state.ts
  client/yarn.lock
Labels: FE, Setting

#61 chore: api 관련 setup
  client/api/auth.ts
  client/api/carts.ts
  client/api/destinations.ts
  client/api/my.ts
  client/api/orders.ts
  client/api/products.ts
  client/api/questions.ts
  client/api/reviews.ts
  client/api/search.ts
  client/api/users.ts
  client/src/utils/axios.ts
  client/yarn.lock
Labels: FE, Setting

#62 chore: mysql infrastructure
  .github/workflows/CI-Server.yml
  .gitignore
  client/.gitignore
  client/package-lock.json
  server/.dockerignore
  server/.eslintrc.js
  server/Dockerfile
  server/package-lock.json
  server/package.json
  server/src/config/properties/properties.ts
  server/src/core-module.ts
  server/src/infra/mysql/mysql-config.ts
  server/src/user/application/auth-service.ts
  server/src/user/domain/user.ts
  server/src/user/domain/users.ts
  server/src/user/entity/user.ts
  server/src/user/infrastructure/password-encoder.ts
  server/src/user/user-module.ts
  server/tsconfig.build.json
  server/tsconfig.json
Labels: BE, Setting

#63 feat: DDD 구조 setup
  server/.eslintrc.js
  server/package-lock.json
  server/src/cart/application/cart-service.ts
  server/src/cart/domain/carts.ts
  server/src/cart/dto/cart-request.ts
  server/src/cart/entity/cart.ts
  server/src/cart/presentation/cart-controller.ts
  server/src/destination/application/destination-service.ts
  server/src/destination/domain/destinations.ts
  server/src/destination/dto/destination-request.ts
  server/src/destination/entity/destination.ts
  server/src/destination/presentation/destination-controller.ts
  server/src/order/application/order-service.ts
  server/src/order/domain/orders.ts
  server/src/order/dto/order-request.ts
  server/src/order/entity/order.ts
  server/src/product/application/product-service.ts
  server/src/product/application/review-service.ts
  server/src/product/domain/products.ts
  server/src/product/domain/questions.ts
  server/src/product/domain/reviews.ts
  server/src/product/domain/search.ts
  server/src/product/dto/product-request.ts
  server/src/product/dto/product-response.ts
  server/src/product/entity/option.ts
  server/src/product/entity/product-detail-image.ts
  server/src/product/entity/product-image.ts
  server/src/product/entity/product.ts
  server/src/product/entity/question.ts
  server/src/product/entity/review.ts
  server/src/product/presentation/product-controller.ts
  server/src/user/domain/wishes.ts
  server/src/user/entity/wish.ts
Labels: BE, Setting

#65 [FE] location 파라미터 인코더, 디코더 구현 및 유틸 테스트코드 작성
  client/src/utils/location/index.ts
  client/src/utils/location/location.test.ts
  client/src/utils/validations/index.ts
  client/src/utils/validations/validations.test.ts
Labels: FE

#66 feat: destination domain 작성
  server/src/destination/application/destination-service.ts
  server/src/destination/domain/destinations.ts
  server/src/destination/dto/destination-request.ts
  server/src/destination/entity/destination.ts
  server/src/destination/presentation/destination-controller.ts
Labels: BE

#68 feat: order domain 작성
  server/src/destination/application/destination-service.ts
  server/src/destination/entity/destination.ts
  server/src/destination/presentation/destination-controller.ts
  server/src/order/application/order-service.ts
  server/src/order/domain/orders.ts
  server/src/order/dto/order-request.ts
  server/src/order/entity/order.ts
  server/src/order/presentation/order-controller.ts
Labels: BE

#70 [FE] 메인 페이지 테스트 코드 작성
  client/src/Pages/Main/BannerSection/Banner/Banner.test.tsx
  client/src/Pages/Main/BannerSection/Banner/index.tsx
  client/src/Pages/Main/BannerSection/BannerSection.test.tsx
  client/src/Pages/Main/BannerSection/index.tsx
  client/src/Pages/Main/GiftSection/Gift/Gift.test.tsx
  client/src/Pages/Main/GiftSection/Gift/index.tsx
  client/src/Pages/Main/GiftSection/GiftList/GiftList.test.tsx
  client/src/Pages/Main/GiftSection/GiftList/index.tsx
  client/src/Pages/Main/GiftSection/GiftSection.test.tsx
  client/src/Pages/Main/ProductSection/ProductSection.test.tsx
  client/src/Pages/Main/ProductSection/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewList/ReviewList.test.tsx
  client/src/Pages/Main/ReviewSection/ReviewList/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewSection.test.tsx
  client/src/Pages/Main/ReviewSection/index.tsx
  client/src/Pages/Main/index.tsx
  client/src/Pages/Order/AddressForm.tsx
  client/src/shared/dummy.ts
  client/src/utils/test-util.tsx
Labels: FE

#71 fix: modal 관련 이슈
  client/src/Components/ModalWrapper/ModalWrapper.test.tsx
  client/src/Components/ModalWrapper/index.tsx
  client/src/Pages/Detail/Question/QuestionModal/QuestionModal.test.tsx
  client/src/Pages/Detail/Question/index.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/Pages/Order/AddressModal/AddressModal.test.tsx
  client/src/Pages/Order/AddressModal/index.tsx
  client/src/Pages/Order/index.tsx
Labels: bug, FE

#74 feat: logo 이미지 변경
  client/src/Components/Footer/index.tsx
  client/src/Components/Header/Menu.tsx
  client/src/Components/Header/Search/index.tsx
  client/src/Components/Header/index.tsx
  client/src/assets/logo.png
  client/src/index.html
  client/src/styles/global-style.ts
  client/src/styles/theme.ts
Labels: FE

#75 mypage 테스트 코드 간단한 것만 작성
  client/src/Components/Item.tsx
  client/src/Pages/Detail/Question/QuestionBox/index.tsx
  client/src/Pages/Detail/Review/ReviewBox/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/OrderList/OrderList.test.tsx
  client/src/Pages/MyPage/ContentArea/contents/OrderList/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Question/Question.test.tsx
  client/src/Pages/MyPage/ContentArea/contents/Question/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Review/Review.test.tsx
  client/src/Pages/MyPage/ContentArea/contents/Review/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Root/Root.test.tsx
  client/src/Pages/MyPage/ContentArea/contents/Root/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/UserInfo/UserInfo.test.tsx
  client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/WishList/WistList.test.tsx
  client/src/Pages/MyPage/ContentArea/contents/WishList/index.tsx
  client/src/Pages/MyPage/ContentArea/index.tsx
  client/src/Pages/MyPage/MyPage.test.tsx
  client/src/Pages/MyPage/Section/Section.test.tsx
  client/src/Pages/MyPage/Section/index.tsx
  client/src/Pages/MyPage/Sidebar/Sidebar.test.tsx
  client/src/Pages/MyPage/Sidebar/index.tsx
  client/src/Pages/MyPage/Table/Table.test.tsx
  client/src/Pages/MyPage/Table/forms/Order/Order.test.tsx
  client/src/Pages/MyPage/Table/forms/ProductOption/ProductOption.test.tsx
  client/src/Pages/MyPage/Table/index.tsx
  client/src/Pages/MyPage/Table/rows/Question/Question.test.tsx
  client/src/Pages/MyPage/Table/rows/Question/index.tsx
  client/src/Pages/MyPage/Table/rows/RecentOrder/RecentOrder.test.tsx
  client/src/Pages/MyPage/Table/rows/Review/Review.test.tsx
  client/src/Pages/MyPage/Table/rows/Review/index.tsx
  client/src/Pages/MyPage/index.tsx
Labels: FE

#72 chore: 상품 불러오기 API
  .gitignore
  server/package-lock.json
  server/src/core-module.ts
  server/src/infra/mysql/mysql-config.ts
  server/src/product/application/product-service.ts
  server/src/product/domain/products.ts
  server/src/product/dto/product-response.ts
  server/src/product/entity/option.ts
  server/src/product/entity/product-detail-image.ts
  server/src/product/entity/product-image.ts
  server/src/product/entity/product.ts
  server/src/product/presentation/product-controller.ts
  server/src/product/product-module.ts
Labels: BE

#73 feat: cart domain 작성
  server/src/cart/application/cart-service.ts
  server/src/cart/domain/carts.ts
  server/src/cart/dto/cart-request.ts
  server/src/cart/entity/cart.ts
  server/src/cart/presentation/cart-controller.ts
Labels: BE

#76 feat: cart/order/destination module 작성
  server/src/cart/cart-module.ts
  server/src/cart/entity/cart.ts
  server/src/core-module.ts
  server/src/destination/destination-module.ts
  server/src/destination/entity/destination.ts
  server/src/order/dto/order-request.ts
  server/src/order/entity/order.ts
  server/src/order/order-module.ts
  server/src/order/presentation/order-controller.ts
  server/src/product/entity/option.ts
Labels: BE

#77 feat: Product 엔티티 수정
  server/src/infra/mysql/mysql-config.ts
  server/src/product/application/product-service.ts
  server/src/product/domain/products.ts
  server/src/product/dto/product-response.ts
  server/src/product/entity/product.ts
  server/src/product/presentation/product-controller.ts
  server/tsconfig.json
Labels: BE

#78 Feature/be auth apis
  server/package.json
  server/src/config/properties/properties.ts
  server/src/core-module.ts
  server/src/destination/destination-module.ts
  server/src/destination/domain/destinations.ts
  server/src/main.ts
  server/src/user/application/auth-service.ts
  server/src/user/application/user-service.ts
  server/src/user/domain/users.ts
  server/src/user/dto/check-email-response.ts
  server/src/user/dto/create-address.ts
  server/src/user/dto/create-user.ts
  server/src/user/dto/signin-request.ts
  server/src/user/dto/signup-request.ts
  server/src/user/entity/user.ts
  server/src/user/infrastructure/password-encoder.ts
  server/src/user/infrastructure/valudation-check.ts
  server/src/user/presentation/auth-controller.ts
  server/src/user/presentation/user-controller.ts
  server/src/user/user-module.ts
  server/yarn.lock
Labels: BE

#80 feat: cart/destination api 수정
  client/config/webpack.config.dev.js
  server/package-lock.json
  server/src/cart/application/cart-service.ts
  server/src/cart/domain/carts.ts
  server/src/cart/dto/cart-request.ts
  server/src/cart/dto/cart-response.ts
  server/src/cart/entity/cart.ts
  server/src/cart/presentation/cart-controller.ts
  server/src/destination/application/destination-service.ts
  server/src/destination/domain/destinations.ts
  server/src/destination/dto/destination-request.ts
  server/src/destination/dto/destination-response.ts
  server/src/destination/entity/destination.ts
  server/src/destination/presentation/destination-controller.ts
  server/src/order/domain/orders.ts
  server/src/user/application/user-service.ts
  server/src/user/dto/create-address.ts
  server/yarn.lock
Labels: BE

#81 feat: cart/destination/order api 구현 완료
  server/src/cart/domain/carts.ts
  server/src/cart/dto/cart-response.ts
  server/src/destination/application/destination-service.ts
  server/src/destination/domain/destinations.ts
  server/src/destination/dto/destination-response.ts
  server/src/order/application/order-service.ts
  server/src/order/domain/orders.ts
  server/src/order/dto/order-request.ts
  server/src/order/dto/order-response.ts
  server/src/order/entity/order.ts
  server/src/order/presentation/order-controller.ts
Labels: BE

#82 hotfix: get product api
  server/package-lock.json
  server/src/product/domain/products.ts
  server/src/product/entity/product.ts
Labels: BE

#83 Question API 작성
  server/src/product/application/product-service.ts
  server/src/product/domain/questions.ts
  server/src/product/dto/question-request.ts
  server/src/product/dto/question-response.ts
  server/src/product/entity/question.ts
  server/src/product/presentation/product-controller.ts
  server/src/product/product-module.ts
Labels: BE

#84 [BE] 토큰 검사하는 middleware 생성
  server/src/core-module.ts
  server/src/destination/application/destination-service.ts
  server/src/destination/domain/destinations.ts
  server/src/destination/dto/destination-request.ts
  server/src/destination/presentation/destination-controller.ts
  server/src/jwt-middleware.ts
  server/src/user/application/auth-service.ts
  server/src/user/application/user-service.ts
  server/src/user/dto/create-address.ts
Labels: BE

#85 feat: Upload product API
  server/package-lock.json
  server/package.json
  server/src/config/properties/properties.ts
  server/src/product/application/product-service.ts
  server/src/product/domain/products.ts
  server/src/product/dto/product-upload-request.ts
  server/src/product/entity/product-image.ts
  server/src/product/entity/product.ts
  server/src/product/infrastructure/s3-repository.ts
  server/src/product/presentation/product-controller.ts
  server/src/product/product-module.ts
Labels: BE

#86 feat: cors setting
  server/src/main.ts
  server/src/product/application/product-service.ts
Labels: BE

#87 feat: react-query setup & my/carts api 작성 및 연결
  client/config/webpack.config.dev.js
  client/package.json
  client/src/Components/ItemInfoBox/ItemInfoBox.test.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Order/OrderBox/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/api/auth.ts
  client/src/api/carts.ts
  client/src/api/destinations.ts
  client/src/api/my.ts
  client/src/api/orders.ts
  client/src/api/products.ts
  client/src/api/questions.ts
  client/src/api/reviews.ts
  client/src/api/search.ts
  client/src/api/users.ts
  client/src/index.tsx
  client/src/shared/type.ts
  client/src/utils/axios.ts
  client/yarn.lock
  server/package-lock.json
  server/src/cart/cart-module.ts
  server/src/cart/domain/carts.ts
  server/src/cart/dto/cart-response.ts
  server/src/cart/dto/product-DTO.ts
  server/src/cart/entity/cart.ts
  server/src/main.ts
  server/src/product/entity/product.ts
  server/src/user/application/my-service.ts
  server/src/user/dto/my-response.ts
  server/src/user/entity/user.ts
  server/src/user/presentation/my-controller.ts
  server/src/user/user-module.ts
Labels: FE

#88 feat: Image service
  server/src/product/application/image-service.ts
  server/src/product/application/product-service.ts
  server/src/product/domain/products.ts
  server/src/product/presentation/image-controller.ts
  server/src/product/product-module.ts
Labels: BE

#89 feat: detailPage & cartPage 데이터 매핑
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/DetailInfo.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/api/carts.ts
  client/src/api/my.ts
  client/src/shared/type.ts
  client/src/utils/axios.ts
  server/src/cart/application/cart-service.ts
  server/src/cart/dto/cart-request.ts
  server/src/cart/dto/cart-response.ts
  server/src/cart/presentation/cart-controller.ts
Labels: FE, BE

#91 feat: 장바구니 / 주문결제 구현
  client/src/Components/Checkbox/Checkbox.test.tsx
  client/src/Components/Checkbox/index.tsx
  client/src/Components/Footer/index.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/ItemInfoBox/ItemInfoBox.test.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Cart/CartBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Order/index.tsx
  client/src/api/carts.ts
  client/src/api/reviews.ts
  client/src/index.tsx
  client/src/store/state.ts
  client/src/styles/theme.ts
Labels: FE

#92 로그인, 회원가입, 로그아웃 구현
  client/package.json
  client/src/App.tsx
  client/src/Components/Header/index.tsx
  client/src/Pages/Login/index.tsx
  client/src/Pages/Signup/index.tsx
  client/src/index.tsx
  client/src/store/state.ts
  client/src/utils/axios.ts
  client/yarn.lock
  server/src/jwt-middleware.ts
  server/src/user/application/auth-service.ts
  server/src/user/application/user-service.ts
  server/src/user/presentation/auth-controller.ts
  server/src/user/presentation/user-controller.ts
Labels: FE, BE

#93 [ API ] my / reviews / questions
  server/src/order/domain/orders.ts
  server/src/order/entity/order.ts
  server/src/product/application/product-service.ts
  server/src/product/domain/questions.ts
  server/src/product/domain/reviews.ts
  server/src/product/dto/question-request.ts
  server/src/product/dto/review-DTO.ts
  server/src/product/dto/review-my-response.ts
  server/src/product/dto/review-request.ts
  server/src/product/dto/review-response.ts
  server/src/product/entity/review.ts
  server/src/product/presentation/product-controller.ts
  server/src/product/product-module.ts
  server/src/user/application/my-service.ts
  server/src/user/domain/users.ts
  server/src/user/dto/my-reqeust.ts
  server/src/user/dto/my-response.ts
  server/src/user/entity/user.ts
  server/src/user/presentation/my-controller.ts
  server/src/user/user-module.ts
Labels: BE

#96 feat: review createAt 추가
  server/src/product/dto/review-DTO.ts
  server/src/product/dto/review-my-response.ts
  server/src/product/dto/review-response.ts
  server/src/product/entity/review.ts
Labels: BE

#97 Item 리디자인 / SVG 추가 및 삭제
  client/src/Components/Item/index.tsx
  client/src/Components/ToggleImageWrapper.tsx
  client/src/assets/addUser.svg
  client/src/assets/brush1.svg
  client/src/assets/brush2.svg
  client/src/assets/brush3.svg
  client/src/assets/brush4.svg
  client/src/assets/brush5.svg
  client/src/assets/brush6.svg
  client/src/assets/cart.svg
  client/src/assets/index.ts
  client/src/assets/loading.svg
  client/src/assets/search.svg
  client/src/assets/user.svg
  client/src/styles/theme.ts
Labels: FE

#95 feat: 배송지 CRUD 구현
  client/src/Components/Address/Popup.tsx
  client/src/Components/Address/index.tsx
  client/src/Components/Checkbox/Checkbox.test.tsx
  client/src/Components/Checkbox/index.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Order/AddressBox/AddressBox.test.tsx
  client/src/Pages/Order/AddressBox/index.tsx
  client/src/Pages/Order/AddressForm.tsx
  client/src/Pages/Order/AddressForm/AddressForm.test.tsx
  client/src/Pages/Order/AddressModal/AddressModal.test.tsx
  client/src/Pages/Order/AddressModal/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/api/destinations.ts
  client/src/api/my.ts
  client/src/shared/dummy.ts
  client/src/shared/type.ts
  client/src/utils/axios.ts
  server/src/cart/dto/cart-response.ts
  server/src/destination/application/destination-service.ts
  server/src/destination/destination-module.ts
  server/src/destination/domain/destinations.ts
  server/src/destination/dto/destination-request.ts
  server/src/destination/dto/destination-response.ts
  server/src/destination/entity/destination.ts
  server/src/destination/presentation/destination-controller.ts
  server/src/user/application/my-service.ts
  server/src/user/application/user-service.ts
  server/src/user/dto/create-address.ts
  server/src/user/entity/user.ts
  server/src/user/presentation/my-controller.ts
Labels: FE

#98 feat: Client CI
  .github/workflows/CI-Client.yml
  client/Dockerfile
  client/package-lock.json
  server/src/config/properties/properties.ts
  server/src/product/domain/products.ts
Labels: FE

#99 feat: 카카오페이 연동
  client/src/App.tsx
  client/src/Pages/Order/index.tsx
  client/src/Pages/OrderSuccess.tsx
  client/src/api/payment.ts
  client/src/utils/axios.ts
  server/package-lock.json
  server/package.json
  server/src/core-module.ts
  server/src/payment/payment-module.ts
  server/src/payment/presentation/payment-controller.ts
Labels: FE, BE

#101 [FE, BE] 로그인, 회원가입 기능 완료
  client/package-lock.json
  client/src/App.tsx
  client/src/Components/APIButton.tsx
  client/src/Components/Address/index.tsx
  client/src/Components/Alert.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/Input/ValidationInput/index.tsx
  client/src/Pages/Login/LoginSection/index.tsx
  client/src/Pages/Login/OAuthLoginSection/index.tsx
  client/src/Pages/Login/index.tsx
  client/src/Pages/Signup/index.tsx
  client/src/api/auth.ts
  client/src/api/users.ts
  client/src/assets/githubLogin.svg
  client/src/assets/googleLogin.svg
  client/src/assets/spinner.png
  client/src/hooks/useInput.ts
  client/src/hooks/useValidation.ts
  client/src/store/state.ts
  client/src/utils/axios.ts
  client/src/utils/error/index.ts
  client/src/utils/util.ts
  client/src/utils/validations/index.ts
  client/yarn.lock
  server/package-lock.json
  server/package.json
  server/src/config/messages.ts
  server/src/config/properties/properties.ts
  server/src/core-module.ts
  server/src/jwt-middleware.ts
  server/src/payment/presentation/payment-controller.ts
  server/src/user/application/auth-service.ts
  server/src/user/application/user-service.ts
  server/src/user/dto/create-user.ts
  server/src/user/entity/user.ts
  server/src/user/infrastructure/github-login.ts
  server/src/user/infrastructure/google-login.ts
  server/src/user/infrastructure/valudation-check.ts
  server/src/user/presentation/auth-controller.ts
  server/src/user/presentation/my-controller.ts
  server/src/user/presentation/user-controller.ts
Labels: FE, BE

#102 feat: api param/body 수정
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Order/AddressForm.tsx
  client/src/api/carts.ts
  client/src/api/destinations.ts
  server/src/cart/presentation/cart-controller.ts
  server/src/destination/dto/destination-request.ts
  server/src/destination/presentation/destination-controller.ts
  server/src/jwt-middleware.ts
  server/src/order/presentation/order-controller.ts
  server/src/user/application/user-service.ts
  server/src/user/dto/create-address.ts
  server/src/user/presentation/my-controller.ts
Labels: FE, BE

#103 Wish api 추가 및 관련 API 수정
  server/src/order/dto/order-response.ts
  server/src/order/entity/order.ts
  server/src/product/dto/question-response.ts
  server/src/product/dto/review-my-response.ts
  server/src/product/dto/review-response.ts
  server/src/product/entity/product.ts
  server/src/product/entity/question.ts
  server/src/product/entity/review.ts
  server/src/user/application/my-service.ts
  server/src/user/domain/wishes.ts
  server/src/user/dto/my-response.ts
  server/src/user/entity/user.ts
  server/src/user/entity/wish.ts
  server/src/user/presentation/my-controller.ts
  server/src/user/user-module.ts
Labels: BE

#104 [FE] Refactor/validation check
  client/src/Components/Header/index.tsx
  client/src/Components/Input/ValidationInput/index.tsx
  client/src/Pages/Order/AddressForm.tsx
  client/src/Pages/Order/AddressForm/AddressForm.test.tsx
  client/src/Pages/Order/AddressForm/index.tsx
  client/src/hooks/useInput.ts
  client/src/shared/type.ts
  server/src/jwt-middleware.ts
Labels: FE

#106 [FE] 환경변수 properties 파일 설정
  client/src/Pages/Login/LoginSection/index.tsx
  client/src/Pages/Login/OAuthLoginSection/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/config/properties.ts
  client/src/utils/axios.ts
Labels: FE

#105 MyPage 관련 API 수정 / 클라이언트 연결
  client/src/App.tsx
  client/src/Components/ImageHoverWrapper/index.tsx
  client/src/Components/Item/index.tsx
  client/src/Pages/Detail/Review/ReviewBox/ReviewBox.test.tsx
  client/src/Pages/Detail/Review/ReviewBox/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewList/ReviewList.test.tsx
  client/src/Pages/MyPage/ContentArea/contents/Question/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Review/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/WishList/index.tsx
  client/src/Pages/MyPage/Table/rows/Review/Review.test.tsx
  client/src/Pages/MyPage/index.tsx
  client/src/api/my.ts
  client/src/assets/wish.svg
  client/src/shared/dummy.ts
  client/src/shared/type.ts
  client/src/styles/theme.ts
  server/src/product/domain/questions.ts
  server/src/product/domain/reviews.ts
  server/src/product/dto/question-response.ts
  server/src/product/dto/review-my-response.ts
  server/src/user/application/my-service.ts
  server/src/user/domain/wishes.ts
  server/src/user/dto/my-response.ts
  server/src/user/presentation/my-controller.ts
Labels: FE, BE

#108 feat: 비로그인시 장바구니/주문결제
  client/src/Components/CartOrderBox/CartOrderBox.tsx
  client/src/Components/CartOrderBox/index.tsx
  client/src/Components/Input/ValidationInput/index.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Cart/CartBox/CartBox.test.tsx
  client/src/Pages/Cart/CartBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Order/AddressForm/index.tsx
  client/src/Pages/Order/AddressModal/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/api/destinations.ts
  client/src/api/orders.ts
  client/src/assets/index.ts
  client/src/assets/kakaopay.png
  client/src/index.tsx
  client/src/shared/type.ts
  client/src/store/state.ts
  server/package-lock.json
  server/src/cart/dto/cart-response.ts
  server/src/destination/presentation/destination-controller.ts
  server/src/jwt-middleware.ts
  server/src/main.ts
  server/src/order/application/order-service.ts
  server/src/order/domain/orders.ts
  server/src/order/dto/order-request.ts
  server/src/order/dto/order-response.ts
  server/src/order/entity/order.ts
  server/src/order/presentation/order-controller.ts
  server/src/product/entity/product.ts
  server/src/user/dto/my-response.ts
Labels: FE

#107 Wish 기능 추가
  client/src/Components/Item/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Root/index.tsx
  client/src/api/my.ts
  server/src/order/domain/orders.ts
  server/src/user/application/my-service.ts
  server/src/user/domain/wishes.ts
  server/src/user/dto/wish-request.ts
  server/src/user/presentation/my-controller.ts
Labels: FE, BE

#109 my info 빼먹은 email 추가
  server/src/user/application/my-service.ts
  server/src/user/domain/wishes.ts
  server/src/user/dto/my-response.ts
  server/src/user/presentation/my-controller.ts
Labels: FE, BE

#111 feat: 주문/결제 구현 완료
  client/src/Components/Checkbox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Order/AddressBox/AddressBox.test.tsx
  client/src/Pages/Order/AddressBox/index.tsx
  client/src/Pages/Order/AddressModal/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/api/destinations.ts
  client/src/api/orders.ts
  client/src/shared/type.ts
  client/src/styles/theme.ts
  server/src/cart/application/cart-service.ts
  server/src/cart/presentation/cart-controller.ts
  server/src/destination/application/destination-service.ts
  server/src/destination/domain/destinations.ts
  server/src/destination/presentation/destination-controller.ts
  server/src/order/application/order-service.ts
  server/src/order/presentation/order-controller.ts
  server/src/payment/presentation/payment-controller.ts
Labels: FE, BE

#112 [FE, BE] Elastic Search 자동완성, 검색 구현 기초작업 완료
  client/src/App.tsx
  client/src/Components/Header/Search/DropDown/AutoCompleteList/index.tsx
  client/src/Components/Header/Search/index.tsx
  client/src/Components/ProductList/index.tsx
  client/src/Pages/Category/index.tsx
  client/src/Pages/Main/BannerSection/Banner/index.tsx
  client/src/Pages/Main/ProductSection/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Root/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/WishList/index.tsx
  client/src/Pages/Search/index.tsx
  client/src/api/search.ts
  client/src/hooks/useDebounce.ts
  client/src/shared/styled.ts
  client/src/shared/type.ts
  server/src/config/messages.ts
  server/src/product/application/product-service.ts
  server/src/product/application/search-service.ts
  server/src/product/domain/products.ts
  server/src/product/dto/product-search-response.ts
  server/src/product/presentation/image-controller.ts
  server/src/product/presentation/product-controller.ts
  server/src/product/product-module.ts
Labels: FE, BE

#113 [FE] 라우팅 리펙토링 및 Search, Category React Query 구현 완료
  client/config/webpack.config.common.js
  client/package.json
  client/src/App.tsx
  client/src/Components/Header/Menu/index.tsx
  client/src/Components/ProductList/index.tsx
  client/src/Pages/Category/index.tsx
  client/src/Pages/Search/index.tsx
  client/src/Router.tsx
  client/src/api/products.ts
  client/src/api/search.ts
  client/src/utils/location/index.ts
  client/yarn.lock
Labels: FE

#114 feat: 결제페이지 수정 및 리뷰 작성 구현
  client/src/Components/CartOrderBox/index.tsx
  client/src/Components/Header/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/Review/ReviewModal/index.tsx
  client/src/Pages/Main/ProductSection/index.tsx
  client/src/Pages/OrderSuccess.tsx
  client/src/Pages/OrderSuccess/index.tsx
  client/src/api/reviews.ts
  client/src/shared/styled.ts
  server/src/main.ts
  server/src/order/entity/order.ts
  server/src/product/application/product-service.ts
  server/src/product/application/review-service.ts
  server/src/product/domain/products.ts
  server/src/product/domain/questions.ts
  server/src/product/domain/reviews.ts
  server/src/product/dto/review-request.ts
  server/src/product/dto/review-response.ts
  server/src/product/entity/review.ts
  server/src/product/presentation/product-controller.ts
  server/src/product/presentation/review-controller.ts
  server/src/product/product-module.ts
  server/src/user/dto/my-response.ts
  server/src/user/user-module.ts
Labels: FE, BE

#115 feat: 상품 등록 페이지 (미완성)
  client/src/App.tsx
  client/src/Pages/Admin/index.tsx
  client/src/Pages/Admin/styles/index.ts
  client/src/assets/box.png
  client/src/assets/clipboard.png
  client/src/assets/dashboard.png
  server/src/cart/entity/cart.ts
  server/src/order/entity/order.ts
  server/src/product/entity/option.ts
  server/src/product/entity/product-detail-image.ts
  server/src/product/entity/product-image.ts
  server/src/product/entity/product.ts
  server/src/product/entity/question.ts
  server/src/user/entity/wish.ts
Labels: FE

#116 feat: 디테일 페이지 기능 구현 완료
  client/src/Components/Checkbox/index.tsx
  client/src/Components/ItemInfoBox/ItemInfoBox.test.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/Question/QuestionBox/QuestionBox.test.tsx
  client/src/Pages/Detail/Question/QuestionBox/index.tsx
  client/src/Pages/Detail/Question/QuestionModal/index.tsx
  client/src/Pages/Detail/Question/index.tsx
  client/src/Pages/Detail/Review/Review.test.tsx
  client/src/Pages/Detail/Review/ReviewBox/index.tsx
  client/src/Pages/Detail/Review/ReviewModal/index.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewList/ReviewList.test.tsx
  client/src/Pages/Main/ReviewSection/index.tsx
  client/src/Pages/MyPage/Table/rows/Question/Question.test.tsx
  client/src/Pages/MyPage/Table/rows/Question/index.tsx
  client/src/api/carts.ts
  client/src/api/products.ts
  client/src/api/questions.ts
  client/src/api/reviews.ts
  client/src/shared/dummy.ts
  client/src/shared/type.ts
  server/src/order/domain/orders.ts
  server/src/order/entity/order.ts
  server/src/order/order-module.ts
  server/src/product/application/product-service.ts
  server/src/product/application/question-service.ts
  server/src/product/application/review-service.ts
  server/src/product/domain/questions.ts
  server/src/product/domain/reviews.ts
  server/src/product/dto/question-request.ts
  server/src/product/dto/question-response.ts
  server/src/product/dto/review-response.ts
  server/src/product/entity/product.ts
  server/src/product/entity/question.ts
  server/src/product/entity/review.ts
  server/src/product/presentation/product-controller.ts
  server/src/product/presentation/question-controller.ts
  server/src/product/product-module.ts
Labels: FE, BE

#118 feat: asset 추가 / 수량 변경 디바운스 적용
  client/src/Components/Header/index.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/assets/etpay.png
  client/src/assets/header_logo.png
  client/src/assets/index.ts
Labels: FE

#120 [FE] 헤더 목업 + 반응형 구현
  client/src/Components/Header/Menu/index.tsx
  client/src/Components/Header/Search/index.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/Input/ValidationInput/index.tsx
  client/src/Components/Item/index.tsx
  client/src/Components/ProductList/index.tsx
  client/src/Pages/Category/Banner/index.tsx
  client/src/Pages/Category/Filter/index.tsx
  client/src/Pages/Category/index.tsx
  client/src/Pages/Detail/Review/ReviewBox/index.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Main/BannerSection/Banner/index.tsx
  client/src/Pages/Main/GiftSection/GiftList/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewList/index.tsx
  client/src/Pages/Main/ReviewSection/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Wishes/WistList.test.tsx
  client/src/shared/dummy.ts
  client/src/shared/styled.ts
  client/src/styles/theme.ts
Labels: FE

#121 Wish 관련 추가사항
  client/src/Components/Item/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/MyPage/ContentArea/OrderList/OrderList.tsx
  client/src/Pages/MyPage/ContentArea/contents/MyMain/index.tsx
  client/src/Pages/MyPage/index.tsx
  client/src/api/my.ts
  client/src/shared/type.ts
  server/src/product/application/product-service.ts
  server/src/product/dto/product-response.ts
  server/src/product/presentation/product-controller.ts
  server/src/product/product-module.ts
  server/src/user/application/my-service.ts
  server/src/user/domain/wishes.ts
  server/src/user/dto/my-response.ts
  server/src/user/presentation/my-controller.ts
Labels: FE, BE

#123 [FE] 카테고리 페이지 구현 완료
  client/src/Components/Header/Menu/index.tsx
  client/src/Components/Header/Search/index.tsx
  client/src/Components/Header/index.tsx
  client/src/Pages/Category/Banner/index.tsx
  client/src/Pages/Category/index.tsx
  client/src/api/products.ts
  client/src/assets/banners/0.gif
  client/src/assets/banners/100.png
  client/src/assets/banners/200.png
  client/src/assets/banners/300.png
  client/src/assets/banners/400.png
  client/src/assets/banners/500.png
  client/src/assets/banners/600.png
  client/src/assets/banners/700.png
  client/src/assets/banners/800.png
  client/src/assets/banners/900.png
  client/src/assets/index.ts
  client/src/shared/dummy.ts
  client/src/styles/global-style.ts
Labels: FE

#122 feat: orderPage / itemInfoBox 분기처리
  client/src/App.tsx
  client/src/Components/CartOrderBox/index.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Components/Progress/index.tsx
  client/src/Components/Rating/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/Question/QuestionBox/QuestionBox.test.tsx
  client/src/Pages/Detail/Question/QuestionBox/index.tsx
  client/src/Pages/Detail/Question/QuestionModal/index.tsx
  client/src/Pages/Detail/Review/ReviewBox/ReviewBox.test.tsx
  client/src/Pages/Detail/Review/ReviewBox/index.tsx
  client/src/Pages/Detail/Review/ReviewModal/index.tsx
  client/src/Pages/Order/AddressBox/AddressBox.test.tsx
  client/src/Pages/Order/AddressBox/index.tsx
  client/src/Pages/Order/AddressForm/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/shared/dummy.ts
  client/src/store/state.ts
  client/src/styles/theme.ts
  client/src/utils/test-util.tsx
  client/src/utils/util.ts
Labels: FE

#124 fix: conflict & process.env
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Detail/DetailInfo.tsx
  client/src/Pages/Detail/index.tsx
  client/src/assets/banners/0.gif
  client/src/assets/banners/100.gif
  client/src/assets/banners/100.png
  client/src/assets/banners/200.gif
  client/src/assets/banners/200.png
  client/src/assets/banners/300.gif
  client/src/assets/banners/300.png
  client/src/assets/banners/400.gif
  client/src/assets/banners/400.png
  client/src/assets/banners/500.gif
  client/src/assets/banners/500.png
  client/src/assets/banners/600.gif
  client/src/assets/banners/600.png
  client/src/assets/banners/700.gif
  client/src/assets/banners/700.png
  client/src/assets/banners/800.gif
  client/src/assets/banners/800.png
  client/src/assets/banners/900.gif
  client/src/assets/banners/900.png
  client/src/assets/index.ts
  client/src/shared/dummy.ts
Labels: bug

#125 [FE] 메인페이지 API 적용 및 Item 반응형 스타일 적용
  client/src/Components/Item/index.tsx
  client/src/Pages/Main/ProductSection/index.tsx
  client/src/api/products.ts
  server/src/product/application/product-service.ts
  server/src/product/domain/products.ts
  server/src/product/dto/product-find-query.ts
  server/src/product/presentation/product-controller.ts
Labels: FE

#126 feat: 장바구니/주문결제 반응형 적용
  client/src/Components/Address/index.tsx
  client/src/Components/CartOrderBox/index.tsx
  client/src/Components/Footer/index.tsx
  client/src/Components/Header/Search/index.tsx
  client/src/Components/Header/index.tsx
  client/src/Components/Input/InputSection/index.tsx
  client/src/Components/Input/ValidationInput/index.tsx
  client/src/Components/Input/index.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/Question/QuestionModal/index.tsx
  client/src/Pages/Detail/Review/ReviewModal/index.tsx
  client/src/Pages/Login/LoginSection/index.tsx
  client/src/Pages/Login/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/api/orders.ts
  client/src/styles/global-style.ts
Labels: FE

#127 fix: 배너 이미지 사이즈 수정
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/assets/banners/0.gif
  client/src/assets/banners/100.gif
  client/src/assets/banners/200.gif
  client/src/assets/banners/300.gif
  client/src/assets/banners/400.gif
  client/src/assets/banners/500.gif
  client/src/assets/banners/600.gif
  client/src/assets/banners/700.gif
  client/src/assets/banners/800.gif
  client/src/assets/banners/900.gif
  client/src/index.tsx
Labels: BE

#130 [FE] 카테고리 정렬, 이미지 Lazy Loading, 스켈레톤 이미지 구현
  client/src/Components/Filter/index.tsx
  client/src/Components/Header/Search/index.tsx
  client/src/Components/Image/index.tsx
  client/src/Components/Item/index.tsx
  client/src/Components/ProductList/index.tsx
  client/src/Components/ToggleImageWrapper.tsx
  client/src/Pages/Category/Banner/index.tsx
  client/src/Pages/Category/Filter/index.tsx
  client/src/Pages/Category/index.tsx
  client/src/Pages/Detail/Question/QuestionBox/index.tsx
  client/src/Pages/Main/BannerSection/Banner/index.tsx
  client/src/Pages/Main/GiftSection/Gift/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Question/index.tsx
  client/src/Pages/Search/index.tsx
  client/src/api/products.ts
  client/src/api/search.ts
  client/src/utils/util.ts
  server/src/product/application/product-service.ts
  server/src/product/application/search-service.ts
  server/src/product/domain/products.ts
  server/src/product/dto/product-find-query.ts
  server/src/product/presentation/product-controller.ts
Labels: FE

#131 question 마이페이지/디테일 작업
  client/src/Components/Rating/index.tsx
  client/src/Pages/Detail/Question/QuestionBox/QuestionBox.test.tsx
  client/src/Pages/Detail/Question/QuestionBox/index.tsx
  client/src/Pages/Detail/Question/QuestionModal/index.tsx
  client/src/Pages/Detail/Question/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Question/index.tsx
  client/src/Pages/MyPage/Table/rows/Question/Question.test.tsx
  client/src/Pages/MyPage/Table/rows/Question/index.tsx
  client/src/Pages/MyPage/Table/rows/index.ts
Labels: FE

#132 feat: detailPage css 수정 및 반응형 적용
  client/src/Components/Button/index.tsx
  client/src/Components/CartOrderBox/index.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/DetailInfo.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/Question/QuestionBox/index.tsx
  client/src/Pages/Detail/Question/index.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Order/index.tsx
  client/src/api/questions.ts
  client/src/styles/global-style.ts
  client/src/styles/theme.ts
Labels: FE

#133 [FE] Feat/infinite scroll 구현 완료
  client/src/Components/APIButton.tsx
  client/src/Components/Filter/index.tsx
  client/src/Components/Image/index.tsx
  client/src/Components/ProductList/index.tsx
  client/src/Pages/Category/Banner/index.tsx
  client/src/Pages/Category/index.tsx
  client/src/Pages/Main/ProductSection/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Wish/index.tsx
  client/src/Pages/Search/index.tsx
  client/src/api/search.ts
  client/src/assets/logo.png
  client/src/hooks/useLazyLoad.ts
  client/src/shared/styled.ts
  client/src/styles/global-style.ts
Labels: FE

#135 Item wish 디바운스
  client/src/Components/Header/Search/DropDown/AutoCompleteList/index.tsx
  client/src/Components/Item/index.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/index.tsx
  client/src/hooks/useDebounce.ts
  client/src/hooks/useDidMountEffect.ts
  client/src/store/state.ts
  server/src/product/application/product-service.ts
  server/src/product/domain/products.ts
  server/src/product/dto/product-element-response.ts
  server/src/product/presentation/product-controller.ts
Labels: FE

#136 feat: myPage / detailPage css 수정
  client/src/Components/Rating/index.tsx
  client/src/Components/SignatureLine.tsx
  client/src/Pages/Category/Banner/index.tsx
  client/src/Pages/Detail/Question/QuestionBox/index.tsx
  client/src/Pages/Detail/Question/QuestionModal/index.tsx
  client/src/Pages/Detail/Review/ReviewBox/index.tsx
  client/src/Pages/Detail/Review/ReviewModal/ReviewModal.test.tsx
  client/src/Pages/Detail/Review/ReviewModal/index.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Order/OrderBox.tsx
  client/src/Pages/MyPage/ContentArea/contents/Order/OrderContainer.tsx
  client/src/Pages/MyPage/ContentArea/contents/Order/index.tsx
  client/src/Pages/MyPage/Section/index.tsx
  client/src/Pages/MyPage/Table/index.tsx
  client/src/Pages/MyPage/index.tsx
  client/src/api/reviews.ts
  client/src/assets/index.ts
  client/src/assets/link-image.ts
  client/src/shared/styled.ts
  server/src/product/application/review-service.ts
  server/src/product/dto/review-request.ts
  server/src/product/dto/review-response.ts
Labels: FE

#191 메인페이지 리뷰
  client/src/Components/ImageHoverWrapper/index.tsx
  client/src/Components/Item/index.tsx
  client/src/Components/ToggleImageWrapper.tsx
  client/src/Pages/Detail/Review/ReviewBox/index.tsx
  client/src/Pages/Detail/Review/ReviewCard/index.tsx
  client/src/Pages/Main/BannerSection/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewList/index.tsx
  client/src/Pages/Main/ReviewSection/index.tsx
  client/src/api/reviews.ts
  server/src/order/dto/order-status-code.ts
  server/src/product/application/review-service.ts
  server/src/product/domain/reviews.ts
  server/src/product/dto/review-request.ts
  server/src/product/presentation/review-controller.ts
  server/src/user/dto/my-response.ts
Labels: FE, BE

#192 feat: 주문내역 구현
  client/src/App.tsx
  client/src/Components/Input/InputSection/index.tsx
  client/src/Components/Input/index.tsx
  client/src/Components/ItemInfoBox/CartSelects.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/Question/index.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/Pages/Login/LoginSection/index.tsx
  client/src/Pages/Login/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
  client/src/Pages/MyPage/Nav/index.tsx
  client/src/Pages/Order/OrderContent/LoggedinContent.tsx
  client/src/Pages/Order/OrderContent/LoggedoutContent.tsx
  client/src/Pages/Order/index.tsx
  client/src/Pages/OrderResult/index.tsx
  server/src/cart/dto/cart-response.ts
  server/src/order/application/order-service.ts
  server/src/order/domain/orders.ts
  server/src/order/dto/order-response.ts
  server/src/payment/presentation/payment-controller.ts
Labels: FE

#193 메인페이지 리뷰 최신/이미지/별5점만
  server/src/product/domain/reviews.ts
Labels: BE

#195 wish 관련 진행 중 공유
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Main/ProductSection/index.tsx
  server/src/product/dto/product-element-response.ts
  server/src/product/dto/product-response.ts
  server/src/user/entity/wish.ts
Labels: bug, FE, BE

#196 feat: myPage 내 정보 수정 구현
  client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
  client/src/Pages/Order/AddressBox/index.tsx
  client/src/Pages/Order/OrderContent/LoggedinContent.tsx
  client/src/Pages/OrderResult/index.tsx
  client/src/api/my.ts
  server/package-lock.json
  server/package.json
  server/src/user/application/my-service.ts
  server/src/user/domain/users.ts
  server/src/user/dto/my-reqeust.ts
  server/src/user/presentation/my-controller.ts
Labels: FE, BE

#197 fix: 수량 numInput 수정 #182
  client/src/Components/ItemInfoBox/CartSelects.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Components/NumInput/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/styles/global-style.ts
Labels: bug, FE

#199 [FE] convertToPhoneNumber 함수 string 없으면 빈 문자열 반환하도록 변경
  client/src/Components/Input/ValidationInput/index.tsx
  client/src/Pages/Main/ProductSection/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
  client/src/Pages/Order/OrderContent/LoggedinContent.tsx
  client/src/utils/util.ts
Labels: FE

#201 refactor: 컴포넌트 폴더 구조 리팩토링
  client/src/App.tsx
  client/src/Components/CartOrderBox/index.tsx
  client/src/Components/Common/Alert/index.tsx
  client/src/Components/Common/Button/APIButton/index.tsx
  client/src/Components/Common/Button/Button.test.tsx
  client/src/Components/Common/Button/index.tsx
  client/src/Components/Common/Checkbox/Checkbox.test.tsx
  client/src/Components/Common/Checkbox/index.tsx
  client/src/Components/Common/Input/InputSection/index.tsx
  client/src/Components/Common/Input/ValidationInput/index.tsx
  client/src/Components/Common/Input/index.tsx
  client/src/Components/Common/NoData/index.tsx
  client/src/Components/Common/NumInput/index.tsx
  client/src/Components/Common/Rating/Rating.test.tsx
  client/src/Components/Common/Rating/index.tsx
  client/src/Components/Common/index.tsx
  client/src/Components/ItemInfoBox/CartSelects.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Components/ProductList/InfiniteScroll/index.tsx
  client/src/Components/ProductList/index.tsx
  client/src/Components/ReviewBox/ReviewBox.test.tsx
  client/src/Components/ReviewBox/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/Question/QuestionModal/index.tsx
  client/src/Pages/Detail/Question/index.tsx
  client/src/Pages/Detail/Review/Progress/Progress.test.tsx
  client/src/Pages/Detail/Review/Progress/index.tsx
  client/src/Pages/Detail/Review/ReviewModal/index.tsx
  client/src/Pages/Detail/Review/index.tsx
  client/src/Pages/Login/LoginSection/index.tsx
  client/src/Pages/Login/OAuthLoginSection/index.tsx
  client/src/Pages/Login/index.tsx
  client/src/Pages/Main/BannerSection/Carousel/index.tsx
  client/src/Pages/Main/BannerSection/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewCard/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewList/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Order/OrderContainer.tsx
  client/src/Pages/MyPage/ContentArea/contents/Question/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Review/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
  client/src/Pages/NotFound/index.tsx
  client/src/Pages/Order/AddressBox/index.tsx
  client/src/Pages/Order/AddressForm/index.tsx
  client/src/Pages/Order/AddressModal/index.tsx
  client/src/Pages/Order/OrderContent/LoggedinContent.tsx
  client/src/Pages/Order/OrderContent/LoggedoutContent.tsx
  client/src/Pages/Signup/index.tsx
  client/src/Pages/Welcome/index.tsx
  client/src/utils/axios.ts
  client/src/utils/error/index.ts
Labels: FE

#204 메인페이지 반응형 / 모바일에 우측에 공간 생기는 문제 해결
  client/src/Components/Common/NoData/index.tsx
  client/src/Components/Item/index.tsx
  client/src/Components/ReviewBox/index.tsx
  client/src/Pages/Main/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Order/OrderBox.tsx
  client/src/Pages/MyPage/ContentArea/contents/Order/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Order/mobile/MobileOrderContainer.tsx
  client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
  client/src/Pages/MyPage/Nav/index.tsx
  client/src/Pages/MyPage/index.tsx
Labels: FE

#206 feat: 내 정보 수정 icon 변경
  client/src/Pages/MyPage/Nav/index.tsx
  client/src/assets/index.ts
  client/src/assets/mypage/myinfo.png
  client/src/assets/mypage/myinfo_active.gif
Labels: FE

#207 [FIX] 자동완성 api를 파라미터에서 쿼리로 변경
  client/src/api/search.ts
  server/src/product/presentation/product-controller.ts
Labels: FE

#208 feat: elasticsearch delete index method
  server/package-lock.json
  server/src/config/messages.ts
  server/src/product/application/product-service.ts
  server/src/product/application/search-service.ts
Labels: BE

#210 chore: assets 정리
  client/src/Pages/Admin/Create/index.tsx
  client/src/Pages/Admin/Product/SearchInput/index.tsx
  client/src/Pages/Admin/index.tsx
  client/src/Pages/Login/OAuthLoginSection/index.tsx
  client/src/assets/addUser.svg
  client/src/assets/delivery.svg
  client/src/assets/good.svg
  client/src/assets/icon/arrow.svg
  client/src/assets/icon/back.svg
  client/src/assets/icon/cart.svg
  client/src/assets/icon/check.svg
  client/src/assets/icon/close.svg
  client/src/assets/icon/delete.svg
  client/src/assets/icon/githubLogin.svg
  client/src/assets/icon/googleLogin.svg
  client/src/assets/icon/home.svg
  client/src/assets/icon/left.svg
  client/src/assets/icon/loading.svg
  client/src/assets/icon/login.svg
  client/src/assets/icon/logout.svg
  client/src/assets/icon/mypage.svg
  client/src/assets/icon/right.svg
  client/src/assets/icon/search.svg
  client/src/assets/icon/triangle.svg
  client/src/assets/icon/wish.svg
  client/src/assets/index.ts
  client/src/assets/info.svg
  client/src/assets/king.svg
  client/src/assets/main-banner/banner1.gif
  client/src/assets/main-banner/banner2.gif
  client/src/assets/main-banner/banner3.gif
  client/src/assets/png/add.png
  client/src/assets/png/box.png
  client/src/assets/png/clipboard.png
  client/src/assets/png/dashboard.png
  client/src/assets/png/delete.png
  client/src/assets/png/et.png
  client/src/assets/png/etpay.png
  client/src/assets/png/header_logo.png
  client/src/assets/png/kakaopay.png
  client/src/assets/png/left-arrow.png
  client/src/assets/png/logo.png
  client/src/assets/png/search.png
  client/src/assets/png/secretpen.png
  client/src/assets/png/spinner.png
  client/src/assets/png/tray.png
  client/src/assets/product.svg
  client/src/assets/ready.svg
  client/src/assets/review.svg
  client/src/shared/styled.ts
Labels: FE

#213 [FE] 페이지 라우팅 + 에러 핸들링 개선중!
  client/src/App.tsx
  client/src/Components/Common/Image/index.tsx
  client/src/Components/Header/Search/index.tsx
  client/src/Components/LoginProvider.tsx
  client/src/Components/ProductList/InfiniteScroll/index.tsx
  client/src/Pages/Cart/index.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Login/index.tsx
  client/src/Pages/Main/ProductSection/index.tsx
  client/src/Pages/MyPage/index.tsx
  client/src/Pages/Signup/index.tsx
  client/src/Router.tsx
  client/src/hooks/index.ts
  client/src/hooks/useDidMountEffect.ts
  client/src/hooks/useLazyLoad.ts
  client/src/store/state.ts
  client/src/utils/error/index.ts
  server/src/config/messages.ts
  server/src/config/properties/properties.ts
  server/src/jwt-middleware.ts
  server/src/product/application/product-service.ts
  server/src/product/presentation/product-controller.ts
  server/src/user/presentation/my-controller.ts
Labels: FE

#214 [FE] 로그아웃 시, item wish box가 Refetch 안되던 버그 수정
  client/src/Components/Item/index.tsx
  client/src/Pages/Main/ProductSection/index.tsx
Labels: bug, FE

#216 feat: product order sorting
  server/package-lock.json
  server/src/product/domain/products.ts
Labels: BE

#215 fix: detail/pagewrapper/banner 반응형 버그픽스
  client/src/Components/Footer/index.tsx
  client/src/Components/ReviewBox/index.tsx
  client/src/Pages/Category/index.tsx
  client/src/Pages/Detail/Question/QuestionBox/index.tsx
  client/src/Pages/Detail/Review/Progress/index.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Main/index.tsx
  client/src/shared/styled.ts
  client/src/shared/type.ts
  server/src/product/application/question-service.ts
  server/src/product/dto/product-response.ts
Labels: bug, BE

#217 feat: ES 인덱스 삭제 & 상품등록 버그 수정
  client/src/Pages/Admin/Create/index.tsx
  server/src/product/application/product-service.ts
  server/src/product/application/search-service.ts
Labels: FE, BE

#218 fix: detailPage 반응형 수정
  client/src/Pages/Detail/index.tsx
Labels: bug, FE

#220 feat: apply exception filter
  server/src/cart/application/cart-service.ts
  server/src/config/filter/exception-handler.ts
  server/src/destination/application/destination-service.ts
  server/src/main.ts
  server/src/order/application/order-service.ts
  server/src/product/application/image-service.ts
  server/src/product/application/product-service.ts
  server/src/product/application/question-service.ts
  server/src/product/application/review-service.ts
  server/src/product/application/search-service.ts
  server/src/product/presentation/product-controller.ts
  server/src/user/application/auth-service.ts
  server/src/user/application/my-service.ts
  server/src/user/application/user-service.ts
  server/src/user/presentation/auth-controller.ts
  server/src/user/presentation/my-controller.ts
  server/src/user/presentation/user-controller.ts
Labels: BE

#221 메인페이지 반응형
  client/src/Components/ImageHoverWrapper/index.tsx
  client/src/Components/Item/index.tsx
  client/src/Components/ProductList/index.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/Main/BannerSection/Banner/index.tsx
  client/src/Pages/Main/BannerSection/Carousel/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewCard/index.tsx
  client/src/Pages/Main/ReviewSection/ReviewList/index.tsx
  client/src/Pages/Main/ReviewSection/index.tsx
  client/src/Pages/Main/index.tsx
Labels: FE

#222 hotfix: add image pk and error logging
  server/src/config/filter/exception-handler.ts
  server/src/user/presentation/my-controller.ts
Labels: BE

#223 Feature/hotfix
  server/src/product/domain/products.ts
  server/src/product/dto/product-element-response.ts
  server/src/product/dto/product-response.ts
  server/src/user/domain/wishes.ts
  server/src/user/entity/wish.ts
Labels: FE, BE

#224 feat: add wishLength column in product
  server/src/product/application/product-service.ts
  server/src/product/domain/products.ts
  server/src/product/entity/product.ts
Labels: BE

#226 feat: wish logic
  client/src/Pages/Admin/Home/index.tsx
  client/src/Pages/Admin/Home/styles/index.ts
  server/src/user/domain/wishes.ts
Labels: BE

#227 feat: 반응형 수정 및 카카오페이 결제 금액 제한
  client/src/App.tsx
  client/src/Components/Common/Alert/index.tsx
  client/src/Components/ItemInfoBox/CartSelects.tsx
  client/src/Components/ItemInfoBox/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
  client/src/Pages/Order/index.tsx
Labels: bug, FE

#228 [FE] Redirect Pages
  client/src/App.tsx
  client/src/Components/ProductList/InfiniteScroll/index.tsx
  client/src/Pages/MyPage/index.tsx
  client/src/Router.tsx
Labels: FE

#229 [FIX] API button
  client/src/Components/Common/Button/APIButton/index.tsx
  client/src/Pages/Detail/Question/QuestionModal/index.tsx
  client/src/Pages/Detail/Review/ReviewModal/index.tsx
  client/src/Pages/Login/LoginSection/index.tsx
  client/src/Pages/Login/OAuthLoginSection/index.tsx
  client/src/Pages/Login/index.tsx
  client/src/Pages/Signup/index.tsx
Labels: bug, FE

#231 Tags 추가 / 메인, 카테고리 반응형 / 품절 관련 추가 / 에러핸들러 개선
  client/src/Components/Item/index.tsx
  client/src/Components/ProductList/InfiniteScroll/index.tsx
  client/src/Components/ProductList/index.tsx
  client/src/Pages/Detail/OptionBox.tsx
  client/src/Pages/Detail/index.tsx
  client/src/Pages/MyPage/ContentArea/contents/Order/OrderContainer.tsx
  client/src/Pages/MyPage/ContentArea/contents/Wish/index.tsx
  client/src/shared/dummy.ts
  client/src/shared/type.ts
  server/src/config/filter/exception-handler.ts
  server/src/product/domain/products.ts
  server/src/product/dto/product-element-response.ts
  server/src/product/entity/product.ts
  server/src/user/application/auth-service.ts
  server/src/user/application/my-service.ts
  server/src/user/domain/wishes.ts
  server/src/user/dto/my-response.ts
Labels: FE, BE

#233 주문 취소 기능 추가
  client/src/Pages/MyPage/ContentArea/contents/Order/OrderBox.tsx
  client/src/Pages/MyPage/ContentArea/contents/Order/OrderContainer.tsx
  client/src/Pages/MyPage/ContentArea/contents/Order/index.tsx
  client/src/api/my.ts
  server/src/config/messages.ts
  server/src/order/domain/orders.ts
  server/src/user/application/my-service.ts
  server/src/user/presentation/my-controller.ts
Labels: FE, BE

#232 [FE] 무한 스크롤 수정
  client/src/Components/ProductList/InfiniteScroll/index.tsx
  server/src/product/domain/products.ts
Labels: bug

#234 [FIX] 헤더 시멘틱 변경 + 카테고리 이미지 고정!
  client/src/Components/Header/index.tsx
  client/src/Pages/Category/Banner/index.tsx
Labels: FE

#235 로딩 추가
  client/src/Pages/MyPage/ContentArea/contents/Review/index.tsx
  client/src/Pages/MyPage/index.tsx
Labels: FE

#237 [FIX] 무한스크롤 관련 버그 수정!
  client/src/Components/ProductList/InfiniteScroll/index.tsx
  client/src/Pages/Category/index.tsx
  client/src/Pages/Search/index.tsx
Labels: bug, FE

#238 hotfix 서치 관련
  server/src/product/application/search-service.ts
  server/src/product/presentation/product-controller.ts
Labels: BE

#239 feat: order 생성시 product/option stock 업데이트
  server/src/order/application/order-service.ts
  server/src/order/order-module.ts
  server/src/product/application/product-service.ts
  server/src/product/domain/products.ts
  server/src/product/product-module.ts
Labels: bug, BE

#240 chore: 품절 박스 border-radius
  client/src/Components/Item/index.tsx
Labels: FE

#241 feat: 어드민 차트
  client/package-lock.json
  client/package.json
  client/src/Components/BarChart/index.tsx
  client/src/Components/BarChart/styles/index.ts
  client/src/Components/DoughnutChart/index.tsx
  client/src/Components/DoughnutChart/styles/index.ts
  client/src/Pages/Admin/Home/index.tsx
  client/src/Pages/Admin/Home/styles/index.ts
  client/src/api/admin.ts
  client/yarn.lock
  server/src/product/application/product-service.ts
  server/src/product/domain/products.ts
  server/src/product/presentation/admin-controller.ts
Labels: FE, BE
